### ISSUE TITLE
DTI tensor, coeff order, saved for "fiberNav"

### ISSUE THREAD

**Issue by StongeEtienne** [scilus/scilpy#104]
In the   "scil_compute_dti_metrics.py"
the script use the fiber Nav order for coef,
should we simply use the default dipy (lower triangle order)

```    if args.tensor:
        # Get the Tensor values and format them for visualisation
        # in the Fibernavigator.
        tensor_vals = lower_triangular(tenfit.quadratic_form)
        correct_order = [0, 1, 3, 2, 4, 5]
        tensor_vals_reordered = tensor_vals[..., correct_order]
        fiber_tensors = nib.Nifti1Image(
            tensor_vals_reordered.astype(np.float32), affine)
        nib.save(fiber_tensors, args.tensor)```

**Comment by frheault** [comment]
I would need input from @jchoude and @arnaudbore on this. I think mostly no one use the FiberNav for Q/A tensor, but I also think mostly no one user Dipy to Q/A tensor too.

We look at the peaks (which are fine) and the recent local tracking support peaks. So I don't know what to do since both ways they aren't use...

**Comment by arnaudbore** [comment]
@GuillaumeTh I thinking about moving to dipy ordering but I want to make sure it won't affect other visualisation scripts. Do you have an idea of what would be effect of such modification ?
