### ISSUE TITLE
--inverse sanity check in RBX script

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#129]
Suggestion: maybe check the --inverse option before doing the streamline computation

Especially important in the single bundle version of the script

**Comment by arnaudbore** [comment]
@frheault any news ?

**Comment by frheault** [comment]
I will check that this week, could be harder than we think. I will try something using barycenter of tractogram and check if it is close enough

**Comment by frheault** [comment]
@arnaudbore Since RBx does a lot of things on the fly it takes around 5-10 minutes to get to the sanity check (after clustering) and the heuristic of barycenter isn't so good.

I would it is not worth it for RBx, I will do the check for `scil_recognize_single_bundle.py` and add a recommendation in RBx to try it first with one bundle as a sanity check.
