### ISSUE TITLE
Update VTK for python 3.8

### ISSUE THREAD

**Issue by GuillaumeTh** [scilus/scilpy#229]
Maybe we can set in the requirements.txt vtk >= 8.1.2 ?

@arnaudbore @jchoude What do you think ?

**Comment by frheault** [comment]
I think that you should have a requirements_singularity.txt containing all `==`
And the real requirements.txt should only contain `>=` that are CentOs, Ubuntu and 2 (recent) MacOs distribution.

Because as of right now we can't use requirements.txt easily on different distribution due to the fact that not all versions exist (I usually change them manually)

If we want (maybe one day) `pip install scilpy` to exist, this is kind of necessary (or else it will only install on a recent Ubuntu setup)

**Comment by frheault** [comment]
@arnaudbore I think this is fixed with the `vtk==8.1.*`

**Comment by arnaudbore** [comment]
Test with #308 -> Python 3.8 for PR308 Nice Job
