### ISSUE TITLE
scil_compute_connectivity.py with include_dpy only

### ISSUE THREAD

**Issue by mdesco** [scilus/scilpy#384]
@frheault would you expect this command line to work?
scil_compute_connectivity.py commit2/commit_1/decompose_commit.h5 wmparc_diff_dil1.5.nii.gz --include_dps commit2/commit_1/ --processes 6

I get the following error:
scil_compute_connectivity.py: error: No connectivity measures were selected, nothing to compute.

If I had a streamline_count output, it works.
scil_compute_connectivity.py commit2/commit_1/decompose_commit.h5 wmparc_diff_dil1.5.nii.gz --include_dps commit2/commit_1/ --processes 6  --streamline_count commit2/commit_1/sc.npy

**Comment by frheault** [comment]
I think that this is desired. Since dps cannot be known in advance it brings out a ton of weird corner case (output files check, the script possibly not doing anything, etc). I think it is best that the script always have a least 1 classical output. Streamlines count is super fast, so I think it should always be there.

**Comment by arnaudbore** [comment]
@mdesco , @frheault should we close this issue ?

**Comment by mdesco** [comment]
Yes you can close.
