### ISSUE TITLE
scil_surface_pft_dipy.py not available anywhere

### ISSUE THREAD

**Issue by bacaron** [scilus/scilpy#555]
Hello,

My name is Brad Caron and I'm a postdoctoral fellow at University of Texas At Austin. I'm working on a project with retinal disorders and was interested in using the Surface Enhanced Tractography (SET) pipeline. I've seen in multiple publications describing the process that the code to do this is available online with documentation, however I cannot for the life of me find said code and/or documentation.

I did find this repository: https://github.com/StongeEtienne/set-nf/, which is the wrapper script used to perform the experiments for the main paper. Within this main file, it calls a function called "scil_surface_pft_dipy", however I cannot find that script in any available repository.

Are there any plans to maybe release this script, and/or provide more documentation online on how to perform SET? I believe I've pieced together enough information to compute the surface seeds, however I'm not entirely sure on how to link the mesh and seeds generated from surface flow methods with dipy's PFT algorithm.

Any help with this would be greatly appreciated!

Thank you,
Brad Caron

**Comment by EmmaRenauld** [comment]
@StongeEtienne , @mdesco You can maybe help me write an answer.

In my case, I ran civet on my data trough CBrain. If you have access to that plateform, that's probably the easiest. You can also run FreeSurfer there.

Then: I downloaded the singularity (I'm not sure where I downloaded it from... @StongeEtienne ?)
and the nextflow that you cited (https://github.com/StongeEtienne/set-nf) and ran

```
nextflow run $SET/main.nf \
    -profile civet2_dkt \
    --tractoflow $tractoflow_output \
    --surfaces $civet_output \
    -with-report report_basic.html \
    --output_dir $set_output \
    -with-singularity $singularity \
    -resume --processes 4 
```

This way, all necessary scripts are contained in the singularity.

** Please note that if you used a recent version of tractoflow, you might need to change line 155 in the main script (https://github.com/StongeEtienne/set-nf/blob/main/main.nf) because PFT_Maps is called PFT_Tracking_Maps in newer versions.

**Comment by bacaron** [comment]
Hello,

I'm so sorry! I meant to close this earlier. I was able to get my questions answered.

Thank you for the help!!

Brad
